format = "2.34+hotfix1"

[[presets]]
id = "b31c1b02-c480-4646-a012-5027af4431b4"
name = "25x_IP-n162_anchorage_FuSi"
version = 1
valid_objectives = [
    "25x",
]
valid_resins = [
    "IP-n162",
]
valid_substrates = [
    "*",
]
writing_speed = 250000.0
writing_power = 50.0
slicing_spacing = 0.8
hatching_spacing = 0.3
hatching_angle = 0.0
hatching_angle_increment = 0.0
hatching_offset = 0.0
hatching_offset_increment = 0.0
hatching_back_n_forth = true
mesh_z_offset = 0.0
grayscale_multilayer_enabled = false
grayscale_layer_profile_nr_layers = 6.0
grayscale_writing_power_minimum = 0.0
grayscale_exponent = 1.0

[presets.properties]

[[resources]]
type = "mesh_file"
id = "0ab4e974-368f-423f-a317-2032eb1a2d41"
name = "Cube"
path = "resources/Cube.stl"
translation = [
    0,
    0,
    0,
]
auto_center = false
rotation = [
    0.0,
    0.0,
    0.0,
]
scale = [
    1.0,
    1.0,
    1.0,
]
enhance_mesh = true
simplify_mesh = false
target_ratio = 100.0

[resources.properties]
original_triangle_count = 12

[[resources]]
type = "mesh_file"
id = "3db402b9-11bd-4c3a-b308-31652ce44cdf"
name = "Cone"
path = "resources/Cone.stl"
translation = [
    0,
    0,
    0,
]
auto_center = false
rotation = [
    0.0,
    0.0,
    0.0,
]
scale = [
    1.0,
    1.0,
    1.0,
]
enhance_mesh = true
simplify_mesh = false
target_ratio = 100.0

[resources.properties]
original_triangle_count = 200

[[resources]]
type = "mesh_file"
id = "f6e7c625-15c5-49ff-b6e8-6db8c883120f"
name = "Cylinder"
path = "resources/Cylinder.stl"
translation = [
    0,
    0,
    0,
]
auto_center = false
rotation = [
    0.0,
    0.0,
    0.0,
]
scale = [
    1.0,
    1.0,
    1.0,
]
enhance_mesh = true
simplify_mesh = false
target_ratio = 100.0

[resources.properties]
original_triangle_count = 400

[[nodes]]
type = "fiber_core_alignment"
id = "1dc8f522-4be3-4fb6-b7ce-131426eff22e"
name = "Fiber aligner 1"
position = [
    0,
    0,
    0,
]
rotation = [
    0.0,
    0.0,
    0.0,
]
children = []
z_scan_range = [
    10.0,
    100.0,
]
center_stage = true
action_upon_failure = "abort"
illumination_name = "process_led_1"
core_signal_lower_threshold = 0.05
core_signal_range = [
    0.1,
    0.9,
]
fiber_radius = 63.5
z_scan_range_sample_count = 8
z_scan_range_scan_count = 4
core_position_offset_tolerance = 6.3500000000000005
detect_light_direction = true

[nodes.properties]

[[nodes]]
type = "edge_alignment"
id = "1faa58f8-ed00-468b-8137-9af79bdcd0c4"
name = "Edge aligner 1"
position = [
    0,
    0,
    0,
]
rotation = [
    0.0,
    0.0,
    0.0,
]
children = [
    "62bf54d0-14fb-4d43-adda-c14ebce217d7",
    "2f66b713-1649-4c0e-8dcd-583fce0096f6",
    "a60610af-47d5-4b32-ba4f-076bd76cde41",
]
center_stage = true
action_upon_failure = "abort"
laser_power = 0.5
scan_area_size = [
    10.0,
    10.0,
]
scan_area_res_factors = [
    1.0,
    1.0,
]
scan_z_sample_distance = 0.1
scan_z_sample_count = 51
angle_search_iteration_count = 2
outlier_threshold = 10.0
xy_position_local_cos = [
    22.0,
    10.0,
]
z_rotation_local_cos = 12.0

[nodes.properties]

[[nodes.alignment_anchors]]
label = "Measurement 1"
offset = 12.0
scan_area_size = [
    50.0,
    10.0,
]

[[nodes.alignment_anchors]]
label = "Measurement 2"
offset = 10.0
scan_area_size = [
    80.0,
    20.0,
]

[[nodes]]
type = "capture"
id = "28a60942-0aa9-4a84-96e3-e55e1345af46"
name = "Capture 2"
position = [
    0,
    0,
    0,
]
rotation = [
    0.0,
    0.0,
    0.0,
]
children = []
laser_power = 0.5
scan_area_size = [
    100,
    100,
]
scan_area_res_factors = [
    1.0,
    1.0,
]
capture_type = "Confocal"

[nodes.properties]

[[nodes]]
type = "structure"
id = "2f66b713-1649-4c0e-8dcd-583fce0096f6"
name = "Lens 1"
position = [
    0,
    0,
    0,
]
rotation = [
    0.0,
    0.0,
    0.0,
]
preset = "b31c1b02-c480-4646-a012-5027af4431b4"
slicing_origin_reference = "scene_bottom"
slicing_offset = 0.0
priority = 0
expose_individually = true
children = []

[nodes.properties]
polynomial_factors_y_last_applied_values = [
    1.0,
    2.0,
]

[nodes.geometry]
type = "lens"
radius = 100.0
height = 50.0
crop_base = true
asymmetric = true
curvature = 0.01
conic_constant = -1.0
curvature_y = 0.01
conic_constant_y = -1.0
polynomial_type = "Normalized"
polynomial_factors = [
    3.0,
    2.0,
    1.0,
    2.0,
    3.0,
    4.0,
]
polynomial_factors_y = [
    1.0,
    2.0,
]
surface_compensation_factors = []
surface_compensation_factors_y = []
nr_radial_segments = 500
nr_phi_segments = 360

[[nodes]]
type = "stage_move"
id = "34f45863-dbb1-4b31-a461-a6d6c1bccfd2"
name = "Stage move 1"
position = [
    0,
    0,
    0,
]
rotation = [
    0.0,
    0.0,
    0.0,
]
children = []
target_position = [
    0,
    0,
    0,
]

[nodes.properties]

[[nodes]]
type = "scene"
id = "356180b4-aa21-41a9-b6aa-0066b37541f8"
name = "Scene 1"
position = [
    0,
    0,
    0,
]
rotation = [
    0.0,
    0.0,
    0.0,
]
children = [
    "dbb5e45f-df6d-46e2-b80f-0a8de6e762ef",
]
writing_direction_upward = true

[nodes.properties]

[[nodes]]
type = "wait"
id = "37a6d454-e580-4737-b329-64eeea7f1509"
name = "Wait 1"
position = [
    0,
    0,
    0,
]
rotation = [
    0.0,
    0.0,
    0.0,
]
children = []
wait_time = 1.0

[nodes.properties]

[[nodes]]
type = "structure"
id = "62bf54d0-14fb-4d43-adda-c14ebce217d7"
name = "Structure 1"
position = [
    0,
    0,
    0,
]
rotation = [
    0.0,
    0.0,
    0.0,
]
preset = "b31c1b02-c480-4646-a012-5027af4431b4"
slicing_origin_reference = "scene_bottom"
slicing_offset = 0.0
priority = 0
expose_individually = false
children = []

[nodes.properties]

[nodes.geometry]
type = "mesh"
resource = "3db402b9-11bd-4c3a-b308-31652ce44cdf"
scale = [
    1.0,
    1.0,
    1.0,
]

[[nodes]]
type = "project"
id = "96721ed5-8331-4331-a6e4-806b4a1efe88"
name = "Project"
position = [
    0,
    0,
    0,
]
rotation = [
    0.0,
    0.0,
    0.0,
]
children = [
    "28a60942-0aa9-4a84-96e3-e55e1345af46",
    "356180b4-aa21-41a9-b6aa-0066b37541f8",
    "1dc8f522-4be3-4fb6-b7ce-131426eff22e",
    "37a6d454-e580-4737-b329-64eeea7f1509",
    "34f45863-dbb1-4b31-a461-a6d6c1bccfd2",
    "c231928d-fa4e-48f4-916a-cb538bcc94c5",
    "aa2017c6-5937-4267-abe5-a916817f5070",
]
version = 7
objective = "25x"
resin = "IP-n162"
substrate = "FuSi"

[nodes.properties]
expanded = true
selection = "aa2017c6-5937-4267-abe5-a916817f5070"

[nodes.meta]
author = ""

[[nodes]]
type = "structure"
id = "a60610af-47d5-4b32-ba4f-076bd76cde41"
name = "Text 1"
position = [
    0,
    0,
    0,
]
rotation = [
    0.0,
    0.0,
    0.0,
]
preset = "b31c1b02-c480-4646-a012-5027af4431b4"
slicing_origin_reference = "scene_bottom"
slicing_offset = 0.0
priority = 1
expose_individually = true
children = []

[nodes.properties]

[nodes.geometry]
type = "text"
text = "enteringsometext"
font_size = 10.0
height = 5.0

[[nodes]]
type = "dose_compensation"
id = "aa2017c6-5937-4267-abe5-a916817f5070"
name = "Dose compensation 1"
position = [
    0,
    0,
    0,
]
rotation = [
    0.0,
    0.0,
    0.0,
]
children = []
position_local_cos = [
    0,
    0,
    0,
]
z_rotation_local_cos = 1000.0
size = [
    200.0,
    100.0,
    100.0,
]
gain_limit = 2.0

[nodes.properties]

[[nodes]]
type = "capture"
id = "c231928d-fa4e-48f4-916a-cb538bcc94c5"
name = "Capture 1"
position = [
    0,
    0,
    0,
]
rotation = [
    0.0,
    0.0,
    0.0,
]
children = []
laser_power = 0.5
scan_area_size = [
    100,
    100,
]
scan_area_res_factors = [
    1.0,
    1.0,
]
capture_type = "Camera"

[nodes.properties]

[[nodes]]
type = "fiber_core_alignment"
id = "dbb5e45f-df6d-46e2-b80f-0a8de6e762ef"
name = "Fiber aligner 2"
position = [
    0,
    0,
    0,
]
rotation = [
    0.0,
    0.0,
    0.0,
]
children = [
    "1faa58f8-ed00-468b-8137-9af79bdcd0c4",
]
z_scan_range = [
    10.0,
    100.0,
]
center_stage = true
action_upon_failure = "abort"
illumination_name = "process_led_1"
core_signal_lower_threshold = 0.05
core_signal_range = [
    0.1,
    0.9,
]
fiber_radius = 63.5
z_scan_range_sample_count = 3
z_scan_range_scan_count = 1
core_position_offset_tolerance = 6.3500000000000005
detect_light_direction = true

[nodes.properties]
